# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 999)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BackgroundStatic = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundStatic.setGeometry(QtCore.QRect(0, -60, 1951, 1091))
        self.BackgroundStatic.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BackgroundStatic.setText("")
        self.BackgroundStatic.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.BackgroundStatic.setScaledContents(True)
        self.BackgroundStatic.setObjectName("BackgroundStatic")
        self.EarthGIF = QtWidgets.QLabel(self.centralwidget)
        self.EarthGIF.setGeometry(QtCore.QRect(1450, 10, 541, 411))
        self.EarthGIF.setText("")
        self.EarthGIF.setPixmap(QtGui.QPixmap("Earth.gif"))
        self.EarthGIF.setScaledContents(True)
        self.EarthGIF.setObjectName("EarthGIF")
        self.TimeGIF = QtWidgets.QLabel(self.centralwidget)
        self.TimeGIF.setGeometry(QtCore.QRect(20, 40, 411, 141))
        self.TimeGIF.setText("")
        self.TimeGIF.setPixmap(QtGui.QPixmap("GIF1Label.gif"))
        self.TimeGIF.setScaledContents(True)
        self.TimeGIF.setObjectName("TimeGIF")
        self.TimeTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.TimeTextBrowser.setGeometry(QtCore.QRect(130, 85, 191, 61))
        self.TimeTextBrowser.setStyleSheet("background-color:Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border-radius:none;\n"
"")
        self.TimeTextBrowser.setObjectName("TimeTextBrowser")
        self.DateGIF = QtWidgets.QLabel(self.centralwidget)
        self.DateGIF.setGeometry(QtCore.QRect(20, 220, 411, 141))
        self.DateGIF.setText("")
        self.DateGIF.setPixmap(QtGui.QPixmap("GIF1Label.gif"))
        self.DateGIF.setScaledContents(True)
        self.DateGIF.setObjectName("DateGIF")
        self.DateTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.DateTextBrowser.setGeometry(QtCore.QRect(137, 270, 191, 61))
        self.DateTextBrowser.setStyleSheet("background-color:Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border-radius:none;\n"
"")
        self.DateTextBrowser.setObjectName("DateTextBrowser")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(640, 820, 331, 141))
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.StartButton.setStyleSheet("background-color: Transparent;")
        self.StartButton.setText("")
        self.StartButton.setObjectName("StartButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(990, 820, 331, 131))
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.ExitButton.setStyleSheet("background-color: Transparent;")
        self.ExitButton.setText("")
        self.ExitButton.setObjectName("ExitButton")
        self.StartButtonLabel = QtWidgets.QLabel(self.centralwidget)
        self.StartButtonLabel.setGeometry(QtCore.QRect(640, 810, 331, 141))
        self.StartButtonLabel.setText("")
        self.StartButtonLabel.setPixmap(QtGui.QPixmap("Start.png"))
        self.StartButtonLabel.setScaledContents(True)
        self.StartButtonLabel.setObjectName("StartButtonLabel")
        self.ExitButtonLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExitButtonLabel.setGeometry(QtCore.QRect(1000, 830, 301, 111))
        self.ExitButtonLabel.setText("")
        self.ExitButtonLabel.setPixmap(QtGui.QPixmap("Quit.png"))
        self.ExitButtonLabel.setScaledContents(True)
        self.ExitButtonLabel.setObjectName("ExitButtonLabel")
        self.AIImageGIF = QtWidgets.QLabel(self.centralwidget)
        self.AIImageGIF.setGeometry(QtCore.QRect(630, 180, 681, 571))
        self.AIImageGIF.setText("")
        self.AIImageGIF.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.AIImageGIF.setScaledContents(True)
        self.AIImageGIF.setObjectName("AIImageGIF")
        self.RoundGIF = QtWidgets.QLabel(self.centralwidget)
        self.RoundGIF.setGeometry(QtCore.QRect(50, 610, 551, 351))
        self.RoundGIF.setText("")
        self.RoundGIF.setPixmap(QtGui.QPixmap("Jarvis_Gui (1).gif"))
        self.RoundGIF.setScaledContents(True)
        self.RoundGIF.setObjectName("RoundGIF")
        self.DayGIF = QtWidgets.QLabel(self.centralwidget)
        self.DayGIF.setGeometry(QtCore.QRect(20, 400, 411, 141))
        self.DayGIF.setText("")
        self.DayGIF.setPixmap(QtGui.QPixmap("GIF1Label.gif"))
        self.DayGIF.setScaledContents(True)
        self.DayGIF.setObjectName("DayGIF")
        self.DateTextBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.DateTextBrowser_2.setGeometry(QtCore.QRect(130, 450, 191, 61))
        self.DateTextBrowser_2.setStyleSheet("background-color:Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border-radius:none;\n"
"")
        self.DateTextBrowser_2.setObjectName("DateTextBrowser_2")
        self.CommandLineDetails = QtWidgets.QLabel(self.centralwidget)
        self.CommandLineDetails.setGeometry(QtCore.QRect(1380, 430, 531, 551))
        self.CommandLineDetails.setText("")
        self.CommandLineDetails.setPixmap(QtGui.QPixmap("exa.gif"))
        self.CommandLineDetails.setScaledContents(True)
        self.CommandLineDetails.setObjectName("CommandLineDetails")
        self.CommandDetailPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.CommandDetailPlainTextEdit.setGeometry(QtCore.QRect(1420, 490, 451, 431))
        self.CommandDetailPlainTextEdit.setStyleSheet("background-color: transparent;\n"
"border-radius:none;")
        self.CommandDetailPlainTextEdit.setObjectName("CommandDetailPlainTextEdit")
        self.JarvisNameTitle = QtWidgets.QLabel(self.centralwidget)
        self.JarvisNameTitle.setGeometry(QtCore.QRect(650, 20, 661, 131))
        self.JarvisNameTitle.setStyleSheet("color: rgb(10, 223, 255);\n"
"font: 75 50pt \"MS Shell Dlg 2\";\n"
"")
        self.JarvisNameTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.JarvisNameTitle.setObjectName("JarvisNameTitle")
        self.BackgroundStatic.raise_()
        self.EarthGIF.raise_()
        self.TimeGIF.raise_()
        self.TimeTextBrowser.raise_()
        self.DateGIF.raise_()
        self.DateTextBrowser.raise_()
        self.StartButtonLabel.raise_()
        self.StartButton.raise_()
        self.ExitButtonLabel.raise_()
        self.ExitButton.raise_()
        self.AIImageGIF.raise_()
        self.RoundGIF.raise_()
        self.DayGIF.raise_()
        self.DateTextBrowser_2.raise_()
        self.CommandLineDetails.raise_()
        self.CommandDetailPlainTextEdit.raise_()
        self.JarvisNameTitle.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.JarvisNameTitle.setText(_translate("MainWindow", "<strong>J.A.R.V.I.S.</strong>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
