# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ProjectImage\splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame\n"
"{\n"
"background-color:rgb(56,58,89);\n"
"border-radius:10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(0, 80, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(14, 215, 255);\n"
"")
        self.label_title.setObjectName("label_title")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(40, 250, 581, 31))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color:rgb(98,114,164);\n"
"color:rgb(200,200,200);\n"
"border-style:none;\n"
"border-radius:10px;\n"
"text-align:center;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"border-radius:10px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.477273, x2:0.99, y2:0.625, stop:0 rgba(2, 200, 255, 255), stop:1 rgba(133, 233, 255, 255))\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(0, 160, 661, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(14, 215, 255);\n"
"")
        self.label_description.setObjectName("label_description")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(50, 280, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(14, 215, 255);\n"
"")
        self.label_loading.setObjectName("label_loading")
        self.label_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QtCore.QRect(360, 350, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(14, 215, 255);\n"
"")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">J.A.R.V.I.S.</span></p></body></html>"))
        self.label_description.setText(_translate("MainWindow", "                     Just A Really Very Intelligent System"))
        self.label_loading.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic;\">loading...</span></p></body></html>"))
        self.label_credits.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Created : </span>Sambit Kumar Sahu </p></body></html>"))
